"""delete is_active column

Revision ID: c1780c19f506
Revises: e6fb5e4974e3
Create Date: 2026-07-28 22:39:49.557527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1780c19f506'
down_revision: Union[str, Sequence[str], None] = 'e6fb5e4974e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'role')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
