"""add chatmessages table

Revision ID: 9d3646f1700c
Revises: de16b71cab7a
Create Date: 2026-08-17 00:06:09.366551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3646f1700c'
down_revision: Union[str, Sequence[str], None] = 'de16b71cab7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatmessages',
    sa.Column('id', sa.Integer(), nullable=False, comment='消息id'),
    sa.Column('session_id', sa.String(length=255), nullable=False, comment='会话id，标记消息属于哪个对话'),
    sa.Column('role', sa.String(length=255), nullable=False, comment='消息角色：system/user/assistant/tool'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessages_session_id'), 'chatmessages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatmessages_session_id'), table_name='chatmessages')
    op.drop_table('chatmessages')
    # ### end Alembic commands ###
